configs:
  cm:
    # -- Enable exec feature in Argo UI
    exec.enabled: true
    # -- Timeout for application operations
    timeout.reconciliation: 180s

  rbac:
    policy.csv: |
      p, role:admin, applications, *, *, allow
      p, role:admin, clusters, get, *, allow
      p, role:admin, exec, create, *, allow
      p, role:admin, logs, get, *, allow
      p, role:admin, projects, get, *, allow
      p, role:admin, repositories, get, *, allow
    policy.default: role:admin

server:
  service:
    type: NodePort

  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/certificate-arn: ${CERTIFICATE_ARN}
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/group.name: ${ingress_group_name}
      alb.ingress.kubernetes.io/load-balancer-attributes: routing.http.drop_invalid_header_fields.enabled=true
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/subnets: ${SUBNET_IDS}
      alb.ingress.kubernetes.io/security-groups: ${SECURITY_GROUP_IDS}
    hosts:
      - ${ARGOCD_DOMAIN}
    paths:
      - /
    pathType: Prefix

  extraArgs:
    - --insecure
    - --rootpath
    - /
