configs:
  cm:
    # -- Enable exec feature in Argo UI
    exec.enabled: true
  

  rbac:
    policy.csv: |
      p, role:admin, applications, *, *, allow
      p, role:admin, clusters, get, *, allow
      p, role:admin, exec, create, *, allow
      p, role:admin, logs, get, *, allow
      p, role:admin, projects, get, *, allow
      p, role:admin, repositories, get, *, allow
    policy.default: role:admin

server:
  service:
    type: NodePort

  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/target-type: instance
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
      alb.ingress.kubernetes.io/group.name: ${ingress_group_name}
      alb.ingress.kubernetes.io/subnets: ${SUBNET_IDS}
      alb.ingress.kubernetes.io/security-groups: ${SECURITY_GROUP_IDS}
    hosts:
      - ${ARGOCD_DOMAIN}
    paths:
      - /
    pathType: Prefix

  extraArgs:
    - --insecure
