kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ${storageclass_name}
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: ${efs_filesystem_id}
  directoryPerms: "700"
  basePath: "/dynamic_pvs"
  subPathPattern: "$${.PVC.name}"
  ensureUniqueDirectory: "false"
  reuseAccessPoint: "true"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer