---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: efs-csi-controller-sa
  namespace: kube-system
  labels:
    app.kubernetes.io/name: aws-efs-csi-driver
    test: test
  annotations:
    eks.amazonaws.com/role-arn: ${eks_efs_role_arn}